#!/usr/bin/env node
/**
 * build-sw.mjs
 *
 * Generates a service worker after the Vite build, with the real hashed asset
 * filenames baked in.
 *
 * Offline is not a nicety here. The site gets used in plant rooms, ceiling
 * voids and basements with no signal, which is exactly where someone needs to
 * check a detail. A reference that only works with reception is a reference
 * that fails when it matters.
 *
 * Strategy:
 *   - app shell and catalog: precached on install, served cache-first
 *   - chapter chunks: cached as they are visited, so reading a chapter at home
 *     makes it available on site the next day
 *   - navigation: falls back to the cached shell, since hash routing means
 *     every route is the same document
 *
 * The cache name embeds a build stamp, so a deploy evicts the old cache
 * instead of serving a stale bundle forever.
 */

import { readdirSync, writeFileSync, statSync, existsSync } from 'node:fs';
import { resolve, dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const DIST = resolve(ROOT, 'dist');
const BASE = '/Thermal-Insulation-Construction/';

if (!existsSync(DIST)) {
  console.error('dist/ not found — run the Vite build first');
  process.exit(1);
}

function walk(dir, out = []) {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) walk(full, out);
    else out.push(full);
  }
  return out;
}

const files = walk(DIST)
  .map((f) => BASE + relative(DIST, f).split('\\').join('/'))
  .filter((f) => !f.endsWith('sw.js'));

// Precache the shell only. Chapter chunks are large and mostly unread at any
// given moment; caching all 43 on install would download the entire book
// before the reader had opened one page.
// Vite emits each lazy chapter chunk as assets/chNN-HASH.js, so the filter has
// to match that name rather than a directory. Getting this wrong precaches the
// entire book on install, which is the opposite of the point.
const isChapterChunk = (f) => /\/ch\d{2}-[\w-]+\.js$/.test(f);

const shell = files.filter(
  (f) =>
    f.endsWith('.html') ||
    f.endsWith('.css') ||
    f.endsWith('.webmanifest') ||
    (f.endsWith('.js') && !isChapterChunk(f)),
);

const deferred = files.filter(isChapterChunk);

const stamp = new Date().toISOString().replace(/\D/g, '').slice(0, 14);

const sw = `// Generated by scripts/build-sw.mjs — do not edit by hand.
const CACHE = 'tic-${stamp}';
const SHELL = ${JSON.stringify(shell, null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches
      .open(CACHE)
      // addAll fails the whole install if any single request fails, so each is
      // added individually. A missing asset should degrade, not break offline.
      .then((cache) => Promise.allSettled(SHELL.map((url) => cache.add(url))))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // Hash routing means every route resolves to the same document, so an
  // offline navigation can always be answered from the cached shell.
  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request).catch(() => caches.match('${BASE}index.html').then((r) => r || Response.error())),
    );
    return;
  }

  event.respondWith(
    caches.match(request).then((cached) => {
      if (cached) return cached;
      return fetch(request)
        .then((response) => {
          // Cache chapter chunks as they are read, so a chapter read at home is
          // available on site tomorrow.
          if (response.ok && url.pathname.includes('/assets/')) {
            const copy = response.clone();
            caches.open(CACHE).then((cache) => cache.put(request, copy));
          }
          return response;
        })
        .catch(() => cached || Response.error());
    }),
  );
});
`;

writeFileSync(resolve(DIST, 'sw.js'), sw, 'utf8');
console.log(
  `service worker written: ${shell.length} shell assets precached, ${deferred.length} chapter chunks cached on first read`,
);
